### PR TITLE
Meteor 0.9+ package system compatibility

### PR DESCRIPTION
**Pull request by cyboman32**
Tested ok for Meteor 0.9
NOT tested for Meteor pre-0.9

And upload to Atmosphere, many people will be happy. Thanks!

### CODE REVIEW

**Comment by Dsyko** [comment]
Hey, Thanks for the PR! I'll take a look and see if I can get this to be backwards compatible and pull it in in a bit.

**Comment by cyboman32** [comment]
Thanks!

And seems I'm done a little mess with CRLFs, sorry :(

**Comment by cristiandley** [comment]
@cyboman32  i made some tests over 0.9 and works fine.

**Comment by cyboman32** [comment]
@cristiandley thanks!

**Pull request merged**
